### ISSUE TITLE
Error in SVM classify

### ISSUE THREAD

**Issue by skomatin** [KevinCoble/AIToolbox#24]
The function classify in the classifier extension of the SVM model by default always throws an error. This is due to a simple logical error in line 128. For type checking, rather than a logical OR, I believe it should be a logical AND.

**Comment by KevinCoble** [comment]
Are you referencing line 127 of SVMExtension.swift?  The line that says:
        `if type != .c_SVM_Classification || type != .ν_SVM_Classification { throw SVMError.invalidModelType }`

I believe you are correct that it should be an 'and', so that it is checking it is not the first valid type 'and' not the second valid type before throwing the exception.

I must be always using 'classifyOne' in my testing, rather than 'classify'.

Thanks for pointing it out.  I will get it changed shortly.

**Comment by skomatin** [comment]
Yep, that is correct!

**Comment by KevinCoble** [comment]
The change has been made.
Thank you for reporting it
