### ISSUE TITLE
Possible to set Regularisation Strength in LogisticRegression

### ISSUE THREAD

**Issue by AJamesPhillips** [KevinCoble/AIToolbox#3]
Firstly, _This is amazing!_.  Thank you very much for this beautiful library.

I've only just started exploring it for the last 6 hours so apologies if this is obvious but I wanted to check it was / wasn't possible to set regularisation strength for LogisticRegression?  Or perhaps I'm just invoking it incorrectly:  https://gist.github.com/AJamesPhillips/07471da4b4be0190d8e34bf357c3c431

There are two tests with similar data (1 st input dimension uniform random distribution, 2 nd input dimension linear trend from 0 to 99, output dimension 0 if 2nd input dimension < 50 else 1).
On the first small data test, the classifier usually predicts an output value of 1.
On the second larger similar data set the tests fail randomly (I assume this is just overfitting).

Many thanks!  (and apologies if this is a stupid question, I'm new to this area in general, both swift and classifiers etc).

**Comment by KevinCoble** [comment]
Thanks for checking out the AIToolbox library!

You're question is, of course, on the one subject in the framework that I am the least familiar with, and have had the hardest time getting results I am happy with - non-linear regression (of which logistic regression is based on).

There is currently no regularization in the non-linear regression class.  As it is a subject I need to learn more about, I haven't extended it more than the bare minimum.  If you (or anyone else out there in the community) have suggestions for implementation or informational material to use to help in the matter, please pass it along - that is why I made the framework open source!

It is of course also possible that I have something wrong in the library too.  I will take the code from your gist and see if I can figure out what is happening.  Due to my schedule, it may take me a couple of days to get the time though.  I'll post back here as soon as I know something.

**Comment by KevinCoble** [comment]
I created a quick playground that used your large data set.  I added the following code after data set creation (see the other playgrounds in the AIToolbox code set for examples if needed):

```
let lr = LogisticRegression(numInputs : 2, solvingMethod: .GaussNewton)
try lr.trainClassifier(data)

let dataView = MLView(frame: CGRect(x: 0, y: 0, width: 480, height: 320))
let dataPlotItem = try MLViewClassificationDataSet(dataset: data)
dataView.setInitialScaleItem(dataPlotItem)

let classifierArea = MLViewClassificationArea(classifier: lr)
classifierArea.granularity = 4
dataView.addPlotItem(classifierArea)

let axisLabels = MLViewAxisLabel(showX: true, showY: true)
dataView.addPlotItem(axisLabels)
dataView.addPlotItem(dataPlotItem)
XCPlaygroundPage.currentPage.liveView = dataView
```

Note that I changed the solution type to Gauss-Newton.  I was unable to get SGD to converge.  I get Gauss-Newton to converge most of the time.  The plot shows an appropriate decision boundary for the two classes.

What I found is there is no way to set convergence criteria on the non-linear solution method of a LogisticRegression.  I will need to add a set of methods to do that.  The default criteria will sometimes work, but often these hyper-parameters will need to be tuned - and right now there is no way to do that.

Yet another in a list of things to do with the framework!  I will leave this issue open until that particular need is addressed.

Again - thanks for trying out the framework.  I obviously need more people using it and commenting (and hopefully contributing!) to get it into even better shape.

**Comment by AJamesPhillips** [comment]
Thanks for the speedy response!  I'll check out your example and see if I can make any headway (I'm completely new to this area myself so can't really help much at the moment.  Saying that I have been using the python sklearn etc as example implementations.  https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/linear_model/logistic.py#L1137 )

And again, thanks for this great contribution!

**Comment by AJamesPhillips** [comment]
Closing for the moment as I'm not working on the project.
